;; Generated by ChatGPT
(defun marcel-hugo/current-timestamp ()
  "Return the current timestamp in ISO 8601 format: 2024-11-24T15:31:36-08:00"
  (let* ((time (current-time))
         (formatted-time (format-time-string "%Y-%m-%dT%H:%M:%S" time))
         (offset (car (current-time-zone time))))
    (concat formatted-time (if (> offset 0)
                               (format "+%02d:%02d" (/ offset 3600) (/ (% offset 3600) 60))
                             (format "-%02d:%02d" (/ (- offset) 3600) (/ (% (- offset) 3600) 60))))))


(defun marcel-hugo/insert-current-timestamp ()
  "Insert the current timestamp in ISO 8601 format at point."
  (interactive)
  (insert (marcel-hugo/current-timestamp)))

(global-set-key (kbd "C-c h") 'marcel-hugo/insert-current-timestamp)
